server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pabloejover/parcial-1-backend-1-terminado.git
          default-label: main
          search-paths: configuration