server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka