server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mscatalog
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**
        - id: msmovie
            uri: lb://movie-service
            predicates:
              - Path=/api/v1/movies/**
        - id: msserie
            uri: lb://serie
            predicates:
              - Path=/api/v1/series/**
  zipkin:
    baseUrl: http://localhost:9411/

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway