server:
  port: 8001

queue:
  serie:
    name: NewMovieQueue

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  zipkin:
    baseUrl: http://localhost:9411/

message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'